import argparse

parser = argparse.ArgumentParser(description="WeirNet")
parser.add_argument("--seed", default=42, help="Seed", type=int)
parser.add_argument("--epochs", default=100, help="Number of epochs", type=int)
parser.add_argument("--batch_size", default=32, help="Batch Size", type=int)
parser.add_argument("--num_workers", default=32, help="Number of workers", type=int)
parser.add_argument("--data_path", default="./Data/PKW_Efficiency_Dataset/combined_data.npz", help="Path of the combined_data.npz file.", type=str)
parser.add_argument("--pc_dir", default="./Data/PKW_Efficiency_Dataset/pc", help="Direction to the point cloud files.", type=str)
parser.add_argument("--stl_dir", default="./Data/PKW_Efficiency_Dataset/stl", help="Direction to the mesh files.", type=str)
# parser.add_argument("--eval_data_path", default=None, help="Eval .npz file path (overrides --data_path).", type=str)
# parser.add_argument("--eval_pc_dir", default=None, help="Eval point cloud dir (overrides --pc_dir).", type=str)
# parser.add_argument("--eval_stl_dir", default=None, help="Eval mesh dir (overrides --stl_dir).", type=str)
parser.add_argument("--exclude_q_min", default=None, help="Min Q to hold out for OOD test (inclusive).", type=float)
parser.add_argument("--exclude_q_max", default=None, help="Max Q to hold out for OOD test (inclusive).", type=float)
parser.add_argument("--lr", default=5e-4, help="Learning rate.", type=float)
parser.add_argument("--dropout", default=0.0, help="Dropout rate.", type=float)
parser.add_argument("--emb_dims", default=1024, help="Dimension", type=int)
parser.add_argument("--k", default=40, help="Nearest Neighbours", type=int)
parser.add_argument("--n_points", default=2048, help="Number of points", type=int)
parser.add_argument("--augmentation", action="store_true", help="Apply Augmentation (default=False).")
parser.add_argument("--model", choices=["PN", "GNN", "DGCNN"], default="PN", help="Surrogate Model (Default=PN).")
parser.add_argument("--resume", action="store_true", help="Resume training from last checkpoint.")
parser.add_argument("--train_fraction", default=1.0, help="Fraction of the training set to use (0,1].", type=float)
args = parser.parse_args()
